image: Visual Studio 2017

init:
- git config --global core.autocrlf true

build_script:
- ps: ci\build.ps1 

test_script:
- ps: ci\test.ps1

artifacts:
- path: artifacts\*.nupkg

deploy:
- provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: QiGaAl+cZPz8jPPRGYRPX05Kj22BuEDTVo+YdPN4KVrGXmCxfIt9nYqgaHEKr8Rg
  skip_symbols: true
  